package main.kotlin.database.firebase

internal data class AuthError(internal val error: FirebaseErrorDetail)